### ISSUE TITLE
Написать модуль, который кладет данные в кликхаус

### ISSUE THREAD

**Issue by Yeloki** [mai-806/Delivery.Metrics#4]
Написать функцию, которая:
1 - принимает какую-то информацию (например текстовую)
2 - отправляет ее в кликхаус

**Comment by SomebodyGit** [comment]
Работоспособном способность модуля проверена с помощью ClickHouse_Consumer: from clickhouse_driver import Client
import pandas as pd
client = Client(host='localhost', port=9000, user='default', password='213790')
query = 'SELECT * FROM on_table'
result = client.execute(query)
df = pd.DataFrame(result, columns=[col[0] for col in client.execute('DESCRIBE on_table')])
print(df)
