### ISSUE TITLE
Создать крон таску, которая будет извлекать данные из ручек и класть их в кафку

### ISSUE THREAD

**Issue by Yeloki** [mai-806/Delivery.Metrics#8]
Взять полученные 2 модуля: обращения к ручкам И отправителя в кафку

Объединить их в одном скрипте.

Добавить запуск данных функций раз в пять секунд в бесконечном цикле

Добавить возможность конфигурации для указания url ручек

**Comment by Kofre-chist** [comment]
Содержание измененного Kafka_producer файла, из-за чего есть какая-никакая уверенность, что и с url-ручками должно заработать.

`from kafka import KafkaProducer
import json

def kafka_producer(topic, data):
	producer = KafkaProducer(bootstrap_servers='localhost:9092',
	value_serializer=lambda v: json.dumps(v).encode('utf-8'))
	producer.send(topic, value=data)
	producer.flush()

# Пример использования
data = {'column1': 31, 'column2': 'daa'}
topic = 'quickstart-events1'
kafka_producer(topic, data)`
